Hw02 express
yulyafed/nodejs-homework-rest-api pull request #1
Opened 2023-01-05 21:05 UTC by yulyafed

2023-01-06 09:11 UTC, KhYulian commented on api.rest
> +###
Для горизонтальної лінії можна використовувати ---

2023-01-06 09:11 UTC, KhYulian commented on contactsSchema/contact.js
> +});
потрібно 2 схеми: для створення, та для оновлення контакту

2023-01-06 09:13 UTC, KhYulian commented on routes/api/contacts.js
> +  });
ви використовуєте next, але не вказали цей параметр. Краще писати  async (req, res, next) завжди

2023-01-06 09:14 UTC, KhYulian commented on routes/api/contacts.js
> +      return res.status(404).json("Not found");
в .json передаємо обєкт - json({message: "Not found."})

2023-01-06 09:15 UTC, KhYulian commented on routes/api/contacts.js
> +    }
if(!contact)

2023-01-06 09:15 UTC, KhYulian commented on routes/api/contacts.js
> +    res.json(contact);
return res.json(contact)

2023-01-06 09:16 UTC, KhYulian requested changes
Потрібне доопрацювання

2023-01-07 16:56 UTC, yulyafed commented on api.rest
> +###
типу замість решіток?

2023-01-07 16:56 UTC, yulyafed commented on api.rest
> +###
типу замість решіток?

2023-01-07 16:57 UTC, yulyafed commented on contactsSchema/contact.js
> +});
зрозуміла)

2023-01-07 16:57 UTC, yulyafed commented on routes/api/contacts.js
> +  });
))))виправляю

2023-01-07 16:57 UTC, yulyafed commented on routes/api/contacts.js
> +      return res.status(404).json("Not found");
дякую

2023-01-07 16:58 UTC, yulyafed commented on routes/api/contacts.js
> +    }
)))) прийняла

2023-01-07 16:58 UTC, yulyafed commented on routes/api/contacts.js
> +    res.json(contact);
тут трохи не зрозуміла чому(((

2023-01-07 17:11 UTC, yulyafed commented on contactsSchema/contact.js
> +});
зробила

2023-01-07 17:11 UTC, yulyafed commented on routes/api/contacts.js
> +  });
виправила

2023-01-07 17:12 UTC, yulyafed commented on routes/api/contacts.js
> +      return res.status(404).json("Not found");
є

2023-01-07 17:12 UTC, yulyafed commented on routes/api/contacts.js
> +    }
є

2023-01-07 17:12 UTC, yulyafed commented on routes/api/contacts.js
> +    res.json(contact);
є

2023-01-07 17:39 UTC, KhYulian commented on api.rest
> +###
Так, # використовується для заголовків

2023-01-07 17:41 UTC, KhYulian commented on routes/api/contacts.js
> +    res.json(contact);
щоб зупинити функцію і уникнути потенційних помилок

2023-01-07 17:42 UTC, KhYulian approved these changes
Чудова робота ❤️

2023-01-07 17:43 UTC, merged