03 mongodb
yulyafed/nodejs-homework-rest-api pull request #2
Opened 2023-01-16 14:51 UTC by yulyafed

2023-01-16 15:37 UTC, KhYulian requested changes
Також переконайтесь, що prettier спрацьовує, бо у вас є пробоеми із стилем коду

2023-01-16 15:37 UTC, KhYulian commented on routes/api/contacts.js
> +    }
Непотрібна перевірка. Для валідації полів у вас є Joi

2023-01-16 15:37 UTC, KhYulian commented on server.js
> +main();
Можна використати IIFE

2023-01-16 15:37 UTC, KhYulian commented on readme.md
> +admin:gvv7UMEbc1JAzJQN
Будь яку чутливу інформацію вкрай небажано пушити в репозиторій. Якщо вам потрібно це зберегти можете додати окремий файл і додати цей файл в гітінор або просто видаліть

2023-01-17 12:59 UTC, yulyafed commented on routes/api/contacts.js
> +    }
зрозуміла дякую

2023-01-17 13:00 UTC, yulyafed commented on readme.md
> +admin:gvv7UMEbc1JAzJQN
дякую видаляю

2023-01-17 13:06 UTC, yulyafed commented on server.js
> +main();
дякую спробую)

2023-01-17 16:24 UTC, KhYulian approved these changes
Чудова робота :)

2023-01-17 16:24 UTC, merged