Hw06 email
yulyafed/nodejs-homework-rest-api pull request #5
Opened 2023-02-05 19:33 UTC by yulyafed

2023-02-05 20:29 UTC, KhYulian requested changes
-

2023-02-05 20:29 UTC, KhYulian commented on validation/userValidation.js
> +};
`const userValidation = (req, res, next) => {
  const { error } = userSchema.validate(req.body);
  if (error) {
    error.status = 400;
    next(error);
    return;
  }
  
  next();
};`

2023-02-06 15:18 UTC, merged

2023-02-06 15:25 UTC, yulyafed commented
я випидково замерджила((вибачте....

2023-02-06 16:42 UTC, KhYulian reviewed
Чудова робота :)